name: brainplayback_task01
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - openssl
  - pip
  - python=3.9.18
  - setuptools
  - pip:
      - nilearn
      - scikit-learn
      - statannotations